### ISSUE TITLE
Can't open file.

### ISSUE THREAD

**Issue by rvlander** [xndcn/atom-debugger#3]
I have a project with test.c and a.out in a root project file.
But when I try to open a debugging session I have an error message with : "Can't open file a.out".

PS. Nice effort. I was about to start such a project and I found yours!

**Comment by xndcn** [comment]
@rvlander Sorry for that, now you have to write down `full/absolute path` of `a.out`...
Please try again, thank you!

**Comment by rvlander** [comment]
Ok I could have it working by launching atom in the executable directory.

**Comment by dpo** [comment]
Same issue here. Starting Atom from the directory where the executable lives doesn't help. Any ideas?
