### ISSUE TITLE
Do you need some help on this?

### ISSUE THREAD

**Issue by rvlander** [xndcn/atom-debugger#4]
I would be glad to have a advanced debugger Atom plugin for GDB. Are you planning to follow your effort? Do you need help ?

**Comment by xndcn** [comment]
@rvlander Sorry for my late reply, I'm busy on something else... Thank you very much! Do you have any ideas?
I want to add `watch` and `call stacks` panels, but I don't have enough time...

**Comment by gideondsouza** [comment]
hey I would also like to pitch in or help out. I was for a while looking to write a gdb frontend just for fun.

I'd just like to know how you really achieved this. Did you use gdb-mi or some npm package or wrote something that interfaces directly with gdb? I'm really not to familiar with coffescript and the atom package system but I would learn and it pitch in here.

:)
